services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: ["npm", "start"]
    networks:
      - link0

networks:
  link0:
    external: true
