services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: icombus2-app
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: ["/bin/sh", "-c", "npm run build && npm start"]
    networks:
      - link0

networks:
  link0:
    external: true
