version: '3.8'

services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: ["npm", "start"]

networks:
  default:
    driver: bridge
